import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID,
  DISCORD_LOG_WEBHOOK_URL,
  PLAYER_ANALYTICS_URL,
  PLAYER_ANALYTICS_USERNAME,
  PLAYER_ANALYTICS_PASSWORD,
} = process.env;

if (
  !DISCORD_TOKEN ||
  !DISCORD_CLIENT_ID ||
  !DISCORD_GUILD_ID ||
  !DISCORD_LOG_WEBHOOK_URL ||
  !PLAYER_ANALYTICS_URL ||
  !PLAYER_ANALYTICS_USERNAME ||
  !PLAYER_ANALYTICS_PASSWORD
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID,
  DISCORD_LOG_WEBHOOK_URL,
  PLAYER_ANALYTICS_URL,
  PLAYER_ANALYTICS_USERNAME,
  PLAYER_ANALYTICS_PASSWORD,
};
